Addina avatar
EBombo/bingo pull request #10
Opened 2021-11-11 20:43 UTC by sebastianmendo1995

Adding user avatar, saving avatar

2021-11-11 21:04 UTC, pyncior requested changes

2021-11-11 21:04 UTC, pyncior commented on src/components/common/Carousel.js
> +    } else {
mejor de usar un "return"

2021-11-11 21:04 UTC, pyncior commented on src/components/common/Carousel.js
> +    } else {
mejor de usar un "return"

2021-11-11 21:04 UTC, pyncior commented on src/pages/login/PinStep.js
> +          components={avatars.map((avatar, index) => (
los key de este map van a hacer conflicto con el componente hijo que tambien tiene como key el index
mejor de usar la url o algo que los haga unicos

2021-11-11 21:04 UTC, pyncior commented on src/components/common/arrowsCarousel.js
> +
solo un salto de linea

2021-11-11 21:04 UTC, pyncior commented on src/components/common/arrowsCarousel.js
> +        })}
nit: no haria mal un pequeño salto de linea como hecho en la linea 18

2021-11-11 22:41 UTC, sebastianmendo1995 commented on src/components/common/Carousel.js
> +    } else {
se hizo el cambio para no utlizar el else

2021-11-11 22:41 UTC, sebastianmendo1995 commented on src/components/common/Carousel.js
> +    } else {
se hizo el cambio solucionando

2021-11-11 22:44 UTC, sebastianmendo1995 commented on src/pages/login/PinStep.js
> +          components={avatars.map((avatar, index) => (
solucionado

2021-11-11 22:45 UTC, sebastianmendo1995 commented on src/components/common/arrowsCarousel.js
> +        })}
resuelto

2021-11-12 13:06 UTC, pyncior approved these changes

2021-11-12 13:26 UTC, merged