fix logOut lobby
EBombo/bingo pull request #30
Opened 2021-11-30 21:49 UTC by anargu

2021-11-30 21:49 UTC, tech-bombo commented
Task linked: [CU-21pux9y aca los botones no están alineados](https://app.clickup.com/t/21pux9y)

2021-11-30 22:24 UTC, pyncior requested changes

2021-11-30 22:24 UTC, pyncior commented on src/pages/lobbies/_lobbyId/index.js
> +    setAuthUserLs({ ...authUserLs, lobby: undefined });
procurar no usar "undefined" en los proyectos, debe haber alguna alternativa mas elegante, quizas solo mapear los datos que queremos que permanezcan

2021-11-30 22:24 UTC, pyncior commented on src/pages/login/index.js
> +  useEffect(() => {
No se si esto sea necesario, cada que la aplicacion recarga se jalan los datos del localStorage en el componente withConfiguration

2021-11-30 22:38 UTC, anargu commented on src/pages/login/index.js
> +  useEffect(() => {
el useEffect colocado ejecuta solo cuando o el authUser no esté especificado o el authUserLs no esté vacío.

2021-12-01 00:27 UTC, pyncior approved these changes

2021-12-01 00:27 UTC, merged