fixing animation
EBombo/bingo pull request #54
Opened 2021-12-22 16:18 UTC by sebastianmendo1995

Fixing last ball animation

2021-12-22 16:18 UTC, tech-bombo commented
Task linked: [CU-1unrde0 efecto lastball](https://app.clickup.com/t/1unrde0)

2021-12-22 16:32 UTC, pyncior requested changes
Parece que la animacion aun no esta funcionando correctamente, cuando se llama a la bolilla se muestra la bolilla pero la animacion del tablero todavia esta corriendo, te adjunto el video

https://user-images.githubusercontent.com/55215092/147124859-dd800913-906c-4f89-8d52-4d55ad361a4c.mov

2021-12-24 16:46 UTC, pyncior requested changes
aun no esta trabajando correctamente por el lado del usuario

https://user-images.githubusercontent.com/55215092/147365326-7a571869-47d8-47f7-863d-9c36ad2699f2.mov

2021-12-27 22:44 UTC, pyncior approved these changes

2021-12-27 22:44 UTC, merged